#!/bin/bash
sooperlooper () {
  while true; do sleep 10;done
  exit 1
}

infoer () {
  bash --version
  vim --version
}

for item in "$@" ; do
    #process item
  if [[ $item == 'version' ]]; then
    infoer
    shift;
  elif [[ $1 == 'ci' ]]; then
    infoer
    exit 0
  elif [[ $1 == 'bash' ]]; then
    /bin/bash -l
    shift;
  elif [[ $item == 'looper' ]]; then
    sooperlooper
    exit 0
  else
    echo "unkown args $@"
    exit 1
  fi
done

exit 0
