#!/bin/bash
sooperlooper () {
  while true; do sleep 10;done
  exit 1
}

infoer () {
  bash --version
  vim --version
}

test1 () {
  TMP=$(mktemp -d)
  cd $TMP
cat <<EOF > $TMP/vim.keys
ggwxjddZZ
EOF
cat <<EOF > $TMP/this.file
one two
three
four
five
EOF
cat <<EOF > $TMP/this.result
one wo
four
five
EOF
  vim -s vim.keys this.file
  diff $TMP/this.result $TMP/this.file &> /dev/null
	if [[ $? == 0 ]]
	then
    exit 0
	else
    exit 1
	fi
}

for item in "$@" ; do
    #process item
  if [[ $item == 'version' ]]; then
    infoer
    shift;
  elif [[ $item == 'ci' ]]; then
    infoer
    test1
  elif [[ $item == 'bash' ]]; then
    /bin/bash -l
    shift;
  elif [[ $item == 'looper' ]]; then
    sooperlooper
    exit 0
  else
    echo "unkown args $@"
    exit 1
  fi
done

exit 0
